---
title: "Copyright des FreeBSD-Projekts"
sidenav: about
---

= Copyright des FreeBSD-Projekts

*Diese deutsche Übersetzung ist nicht rechtlich bindend.* +
*Im Zweifelsfall gilt nur die link:../../../copyright/freebsd-license[englischsprachige Originalversion]!*

Copyright 1992-2023 The FreeBSD Project.

Die Weitergabe und Verwendung in Quell- und Binärform, mit oder ohne Änderungen, ist erlaubt, sofern die folgenden Bedingungen erfüllt sind:

. Die Weitergabe des Quellcodes muss den obigen Copyright-Vermerk, diese Liste der Bedingungen und den folgenden Haftungsausschluss enthalten.
. Weiterverteilungen in binärer Form müssen den obigen Copyright-Hinweis, diese Liste der Bedingungen und den folgenden Haftungsausschluss in der Dokumentation und/oder anderen mit der Verteilung gelieferten Materialien wiedergeben.

DIESE SOFTWARE WIRD VOM AUTOR UND DEN MITWIRKENDEN SO ZUR VERFÜGUNG GESTELLT, WIE SIE IST, UND JEDE AUSDRÜCKLICHE ODER STILLSCHWEIGENDE GARANTIE, EINSCHLIESSLICH, ABER NICHT BESCHRÄNKT AUF DIE STILLSCHWEIGENDE GARANTIE DER MARKTGÄNGIGKEIT UND DER EIGNUNG FÜR EINEN BESTIMMTEN ZWECK, WIRD ABGELEHNT. IN KEINEM FALL HAFTEN DER AUTOR ODER DIE MITWIRKENDEN FÜR DIREKTE, INDIREKTE, ZUFÄLLIGE, BESONDERE, BEISPIELHAFTE ODER FOLGESCHÄDEN (EINSCHLIESSLICH, ABER NICHT BESCHRÄNKT AUF DIE BESCHAFFUNG VON ERSATZGÜTERN ODER -DIENSTLEISTUNGEN, NUTZUNGS-, DATEN- ODER GEWINNVERLUSTE ODER GESCHÄFTSUNTERBRECHUNGEN), WIE AUCH IMMER DIESE VERURSACHT WURDEN UND AUF WELCHER HAFTUNGSTHEORIE SIE BERUHEN, SEI ES DURCH VERTRAG, VERSCHULDENSUNABHÄNGIGE HAFTUNG ODER UNERLAUBTE HANDLUNGEN (EINSCHLIESSLICH FAHRLÄSSIGKEIT ODER SONSTIGES), DIE IN IRGENDEINER WEISE AUS DER NUTZUNG DIESER SOFTWARE ENTSTEHEN, SELBST WENN AUF DIE MÖGLICHKEIT SOLCHER SCHÄDEN HINGEWIESEN WURDE.

Die in der Software und der Dokumentation enthaltenen Ansichten und Schlussfolgerungen sind die der Autoren und sollten nicht als offizielle Politik des FreeBSD-Projekts interpretiert werden, weder ausdrücklich noch implizit.

link:..[Legal Home]
