---
title: "FreeBSD Project Administration and Management"
sidenav: about
---

include::shared/authors.adoc[]

= FreeBSD-Projektverwaltung und -management

== Einführung

Diese Seite enthält eine Auflistung von Teams, Gruppen und Einzelpersonen innerhalb des FreeBSD Projects und beschreibt deren Rolle und Verantwortungsbereiche innerhalb des Projekts. Außerdem finden Sie hier Tätigkeitsbeschreibungen sowie Kontaktinformationen. Um Missverständnissen vorzubeugen, wurden die Bezeichnungen der Teams und Gruppen *nicht* übersetzt.

* Projektmanagement
** <<t-core, Core Team>>
** <<t-doceng, Documentation Engineering Team>>
** <<t-portmgr, Port Management Team>>
** <<t-ports-secteam, Ports Security Team>>
** <<t-pkgmgr, Package Manager Team>>
* Release Engineering
** <<t-re, Primary Release Engineering Team>>
* Teams
** <<t-donations, Donations Team>>
** <<t-secteam, Security Team>>
** <<t-vendor, Vendor Relations>>
* Sekretäre
** <<t-core-secretary, Core Team Secretary>>
** <<t-doceng-secretary, Documentation Engineering Team Secretary>>
** <<t-portmgr-secretary, Port Management Team Secretary>>
* Interne Verwaltung
** <<t-accounts, Accounts Team>>
** <<t-backups, Backup Administrators>>
** <<t-bugmeister, Bugmeisters>>
** <<t-clusteradm, Cluster Administrators>>
** <<t-dnsadm, DNS Administrators>>
** <<t-forum-admins, Forum Administrators>>
** <<t-git, Git Administrators>>
** <<t-github-automation, GitHub Repository Mirror>>
** <<t-jenkins-admin, Jenkins Continuous Integration Testing Administrators>>
** <<t-mirror-admin, FTP/WWW Mirror Site Coordinators>>
** <<t-phabric-admin, Phabricator Code Review Administration>>
** <<t-postmaster, Postmaster Team>>
** <<t-subversion, Subversion Administrators>>
** <<t-webmaster, Webmaster Team>>
** <<t-wiki, Wiki Admin Team>>

'''

[[t-core]]
== FreeBSD Core Team <core@FreeBSD.org>

Das FreeBSD Core Team bildet den Vorstand des Projekts, das für die Festlegung der allgemeinen Ziele und der Ausrichtung des Projekts sowie für die Verwaltung bestimmter Bereiche der FreeBSD-Projektlandschaft verantwortlich ist.
Das Core Team wird von den aktiven Entwicklern des Projekts gewählt.

* {bapt} (Verbindung zum Security Team)
* {bcr} (Verbindung zur FreeBSD Foundation)
* {emaste} (Verbindung zum Primary Release Engineering Team)
* {grog}
* {jhb} (Verbindung zum CI-Team)
* {lwhsu} (Verbindung zum Documentation Engineering Team)
* {manu} (Verbindung zum Port-Management-Team)
* {tcberner} (Verbindung zum Cluster-Administratoren-Team)
* {0mp} (Verbindung zum Bugmeister Team)

[[t-doceng]]
== FreeBSD Documentation Engineering Team <doceng@FreeBSD.org>

Das FreeBSD Documentation Engineering Team legt die Vorgaben für die Committer des Dokumentations-Projekts fest und kontrolliert auch deren Einhaltung.
Die https://www.freebsd.org/internal/doceng/[Documentation Engineering Team-Satzung] beschreibt die Aufgaben und Verantwortlichkeiten dieses Teams genauer.

* {gjb}
* {carlavilla}
* {blackend}
* {dbaio}
* {bcr}
* {hrs}
* {fernape} (Sekretär)

[[t-portmgr]]
== FreeBSD Port-Management-Team <portmgr@FreeBSD.org>

Die Hauptaufgabe des FreeBSD Port-Management-Teams besteht darin, sicherzustellen, dass die FreeBSD Port-Entwickler-Gemeinschaft eine nützliche, stabile, aktuelle und voll funktionsfähige Ports-Sammlung zur Verfügung stellt.
Seine sekundäre Aufgabe ist es, die Zusammenarbeit von Entwicklern und  Committern zu koordinieren.
Die https://www.freebsd.org/portmgr/charter/[Port-Management-Team-Satzung] beschreibt die Aufgaben und Verantwortlichkeiten des Port-Management-Teams ausführlicher.

* {bapt}
* {bofh}
* {mat} (Verbindung zu den Cluster Administrators)
* {pizzamig}
* {rene} (Sekretär)
* {tcberner}

'''

[[t-ports-secteam]]
== FreeBSD Ports Security Team <ports-secteam@FreeBSD.org>

Die Hauptaufgabe des FreeBSD Ports Security Teams besteht darin, schnell auf Sicherheitsvorfälle zu reagieren, die die FreeBSD-Port-Sammlung betreffen, und die FreeBSD-Benutzergemeinschaft zu schützen, indem es die Anwender über Bugs, Schwachstellen, bekannte Angriffe und andere Risiken auf dem Laufenden hält.
Weitere Informationen finden Sie auf der https://wiki.freebsd.org/PortsSecteam[Wiki-Seite des Ports Security Teams].

* {fluffy}
* {joneum}
* {riggs}

'''

[[t-pkgmgr]]
== FreeBSD Package Manager Team <pkgmgr@FreeBSD.org>

Die Hauptaufgabe des FreeBSD Package Manager Team besteht darin, sicherzustellen, dass das gesamte Ports-System funktionsfähig bleibt. Dazu gehören das Ausführen von Test-Builds mit vorgeschlagenen Änderungen, das Zurücksetzen/Beheben von fehlerhaften Commits, die die Builds beschädigen, die Wartung des automatisierten Paketerstellungs-Clusters und die Bereitstellung der resultierenden Pakete zum Download durch FreeBSD-Benutzer.

* {antoine}
* {bdrewery}

'''

[[t-re]]
== Primäres Primary Release Engineering Team <re@FreeBSD.org>

Das primäre Primary Release Engineering Team erstellt und veröffentlicht die Zeitpläne für die Bereitstellung der offiziellen FreeBSD-Releases, verfügt "Code Freezes" und wartet die verschiedenen `releng/*`-Zweige.
Die https://www.freebsd.org/releng/charter/[Primary Release Engineering Team-Satzung] beschreibt die Aufgaben und Verantwortlichkeiten des primären Primary Release Engineering Teams ausführlicher.

* {gjb} (Leiter)
* {kib}
* {blackend}
* {karels}
* {delphij}
* {cperciva} (Stellvertretender Leiter)

[[t-donations]]
== Donations Team <donations@FreeBSD.org>

Das Spendenteam ist verantwortlich für die Beantwortung von Spendenangeboten, die Festlegung von Spendenrichtlinien und -verfahren sowie die Koordination von Spendenangeboten mit der FreeBSD-Entwicklergemeinde.
Eine detailliertere Beschreibung der Aufgaben des Donations Teams finden Sie unter https://www.freebsd.org/donations/[Verbindung zum FreeBSD Donations Team].

* {gahr}
* {bhughes}
* {adridg}

[[t-secteam]]
== Security Team <secteam@FreeBSD.org>

Das FreeBSD Security Team (unter der Leitung des Sicherheitsbeauftragten) ist dafür verantwortlich, die FreeBSD-Gemeinschaft über Fehler, Schwachstellen und Sicherheitsrisiken in den FreeBSD-Repositories src und ports zu informieren und Informationen zu verbreiten, die für den sicheren Betrieb von FreeBSD-Systemen erforderlich sind.
Darüber hinaus ist es für die Behebung von Software-Fehlern, die die Sicherheit von FreeBSD beeinträchtigen, und für die Herausgabe von Sicherheitshinweisen verantwortlich.
Die https://www.FreeBSD.org/security/charter/[Satzung für den FreeBSD Sicherheitsbeauftragten] beschreibt seine Aufgaben und Verantwortlichkeiten ausführlicher.

* {gordon} (Sicherheitsbeauftragter)
* {bapt} (Verbindung zum Core-Team)
* {delphij} (emeritierter Sicherheitsbeauftragter, Verbindung zum Primary Release Engineering Team)
* {des} (emeritierter Sicherheitsbeauftragter)
* {gjb} (Verbindung zum Cluster-Administratoren-Team)
* {emaste} (Stellvertreter des Sicherheitsbeauftragten)
* {markj}
* {oshogbo}
* {philip}

[[t-vendor]]
== Vendor Relations <vendor-relations@FreeBSD.org>

Das Lieferantenbeziehungs-Team ist für die Bearbeitung von E-Mails von Hardware- und Softwareanbietern verantwortlich.
E-Mails, die an die Mail-Adresse des  <vendor-relations@FreeBSD.org> gesendet werden, werden nicht nur an die FreeBSD Foundation, sondern auch an das FreeBSD Core Team weitergeleitet.

'''

[[t-core-secretary]]
== Core Team Secretary <core-secretary@FreeBSD.org>

Der Sekretär des FreeBSD Core-Teams ist ein nicht stimmberechtigtes Mitglied des Core-Teams, das dafür verantwortlich ist, die Arbeit des Core-Teams zu dokumentieren, die Projekt-Agenda im Auge zu behalten, Nicht-Core-Mitglieder im Namen des Core-Teams zu kontaktieren, E-Mails an das Core-Team zu senden und mit dem Administartoren-Team für die Einrichtung von Committer-Accounts in Kontakt zu treten.
Der Sekretär des Core-Teams ist auch dafür verantwortlich, monatliche Statusberichte zu verfassen und an die FreeBSD-Entwicklergemeinde zu versenden, die eine Zusammenfassung der letzten Entscheidungen und Aktionen des Core-Teams enthalten.

* {carlavilla}

[[t-doceng-sekretary]]
== Documentation Engineering Team Secretary <doceng-secretary@FreeBSD.org>

Der Sekretär des FreeBSD okumentations-Engineering-Teams ist ein nicht stimmberechtigtes Mitglied dieses Teams, das für die Dokumentation der Arbeit des Teams verantwortlich ist, den Überblick über die Abstimmungsvorgänge behält und als Schnittstelle zu den anderen Teams, insbesondere zu den Administratoren- und Core-Teams, fungiert.

* {fernape}

[[t-portmgr-secretary]]
== Port Management Team Secretary <portmgr-secretary@FreeBSD.org>

Der Sekretär des Port-Management-Teams ist ein nicht stimmberechtigtes Mitglied dieses Teams, das dafür verantwortlich ist, die Arbeit des Teams zu dokumentieren, die Abstimmungsvorgänge zu verfolgen und als Schnittstelle zu den anderen Teams, insbesondere zu den Administratoren-Teams und dem Core-Team, zu fungieren.
Der Sekretär des Port Management Teams ist auch dafür verantwortlich, monatliche Statusberichte zu verfassen und an die FreeBSD-Entwicklergemeinde zu senden, die eine Zusammenfassung der letzten Entscheidungen und Aktionen des Port-Management-Teams enthalten.

* {rene}

'''

[[t-accounts]]
== Accounts Team <accounts@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Das Accounts-Team ist für die Einrichtung von Accounts für neue Committer im Projekt verantwortlich.
Anfragen für neue Accounts werden nicht ohne die ordnungsgemäße Genehmigung der entsprechenden Stelle bearbeitet.

E-Mails, die an das Accounts-Team gesendet werden, werden von den Cluster-Administratoren bearbeitet.

[[t-backups]]
== Backup Administrators <backups@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die Backup-Administratoren kümmern sich um die Datensicherung auf dem FreeBSD-Cluster.

E-Mails, die an das Backup-Administratoren-Team gesendet werden, werden von den Cluster-Administratoren bearbeitet.

[[t-bugmeister]]
== Bugmeisters <bugmeister@FreeBSD.org>

Das Bugmeister-Team ist dafür verantwortlich, dass die Software zur Verwaltung von Problemberichten  einwandfrei funktioniert, dass die Einträge korrekt kategorisiert sind und dass es keine ungültigen Einträge gibt.

* {eadler}
* {gavin}
* {linimon}
* {mva}
* {0mp}

[[t-clusteradm]]
== Cluster Administrators <clusteradm@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die Cluster-Administratoren sind für die Wartung der Computer und Dienste verantwortlich, auf die das Projekt für seine verteilte Arbeit und Kommunikation angewiesen ist.
Fragen, die die Infrastruktur des Projekts oder die Einrichtung neuer Maschinen oder Dienste betreffen, sollten an sie gerichtet werden.
Dieses Team wird vom leitenden Cluster-Administrator geleitet, dessen Aufgaben und Verantwortlichkeiten in der https://www.freebsd.org/internal/clusteradm/[Clusterverwaltungs-Satzung] näher beschrieben sind.

* {allanjude}
* {allanjude}
* {bapt}
* {bofh}
* {dbaio}
* {dhw}
* {gjb}
* {lwhsu}
* {peter}
* {philip}
* {zi}  (Leitung)

Bitte erwägen Sie, einen der spezifischeren Aliase (z. B. accounts@, dnsadm@, mirror-admin@,...) oder https://bugs.freebsd.org/submit/[Öffnen eines Fehlerberichts] zu verwenden, um Probleme mit der Cluster-Infrastruktur zu melden.  Wählen Sie "Services" und dann "Core Infrastructure" aus.

[[t-dnsadm]]
== DNS Administrators <dnsadm@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die DNS-Administratoren sind für die Verwaltung von DNS und den zugehörigen Diensten verantwortlich.

E-Mails, die an DNS Administrators gesendet werden, werden derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet.

[[t-forum-admins]]
== Forum Administrators <forum-admins@FreeBSD.org>

Die Forum-Administratoren betreuen das Internetforum des FreeBSD-Projekts, das sich in https://forums.freebsd.org/ befindet, und leiten die Gruppe von Moderatoren, die die Relevanz und Qualität der Inhalte des Forums sicherstellen.

* {brd}
* {danger}
* {dutchdaemon}
* {lme}

[[t-git]]
== Git Administrators <gitadm@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die FreeBSD Git-Administratoren sind für die Aufrechterhaltung des Zustands der Git-Repositories verantwortlich.

E-Mails an die Git Administrators werden von den Cluster Administrators bearbeitet.

Bitte https://bugs.freebsd.org/submit/[Fehlerbericht öffnen], um Probleme mit den Git-Repositories zu melden.  Wählen Sie "Services" und dann "Core Infrastructure" aus.

[[t-github-automation]]
== GitHub Repository Mirror <github-automation@FreeBSD.org>

Das GitHub Repository Mirror-Team beaufsichtigt den Export des Inhalts des FreeBSD-Quellcode-Repositorys in die schreibgeschützten Repository-Instanzen auf GitHub

* {koobs}
* {mva}
* {robak}
* {rodrigc}
* {uqs}

[[t-jenkins-admin]]
== Jenkins Continuous Integration Testing Administrators <jenkins-admin@FreeBSD.org>

Die Jenkins-Administratoren pflegen die Continuous Integration- und Test-Infrastruktur für das FreeBSD-Projekt.
Dazu gehört die Verwaltung der Jenkins-Instanz und der Verarbeitungsaufträge, die die Builds und Tests ausführen.

* {bapt}
* {brd}
* {brooks}
* {lwhsu}
* {swills}

[[t-mirror-admin]]
== FTP/WWW Mirror Site Coordinators <mirror-admin@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die FTP/WWW Mirror Site Coordinators koordinieren die Arbeit der Administratoren von FTP/WWW-Spiegelservern, um sicherzustellen, dass sie aktuelle Versionen der Software verteilen, dass sie in der lahge sind, auch größere Updates zu verwalten, und dass es für die breite Öffentlichkeit einfach ist, den nächstgelegenen FTP/WWW-Mirror zu finden.

E-mails an das Mirror Site Coordinators Team  werden von den link:#t-clusteradm[Cluster-Administratoren] bearbeitet.

Bitte einen https://bugs.freebsd.org/submit/[Fehlerbericht] öffnen, um Probleme mit der Spiegelinfrastruktur zu melden.  Wählen Sie "Services" und dann "FTP/WWW-Sites & Mirrors".

[[t-phabric-admin]]
== Phabricator Code Review Application Administrators <phabric-admin@FreeBSD.org>

Die Phabricator-Administratoren sind für die Wartung der FreeBSD-Instanz des Online-Code-Review-Tools Phabricator verantwortlich, die unter https://reviews.freebsd.org/ erreichbar ist.

* {allanjude}
* {bofh}
* {eadler}
* {emaste}
* {jtl}
* {lwhsu}
* {mat}
* {pi}

Bei Problemen mit Phabricator erstellen Sie bitte einen https://bugs.freebsd.org/submit/[Fehlerbericht] und wählen Sie "Services" und dann "Code Review".

[[t-postmaster]]
== Postmaster Team <postmaster@FreeBSD.org>

Das Postmaster-Team ist dafür verantwortlich, dass die E-Mails korrekt an die E-Mail-Adressen der Committer zugestellt werden, dass die Mailinglisten funktionieren und sollte Maßnahmen gegen mögliche Störungen der Projekt-Mail-Dienste umsetzen, wie z.B. Troll-, Spam- und Virenfilter.

* {bapt}
* {krion}
* {ler}
* {philip}
* {pi}
* {vsevolod}
* {zi}

[[t-subversion]]
=== Subversion Administrators <svnadm@FreeBSD.org>
////
Admins E-Mail-Aliase absichtlich unvollständig gelassen
////

Die FreeBSD Subversion-Administratoren sind für die Aufrechterhaltung des Zustands der Subversion-Projektarchive verantwortlich.

E-mails an das Subversion Administration Team werden von den link:#t-clusteradm[Cluster-Administratoren] bearbeitet.

Bitte öffnen Sie einen https://bugs.freebsd.org/submit/[Fehlerbericht], um Probleme mit den Subversion-Projektarchiven zu melden.  Wählen Sie "Services" und dann "Core Infrastructure" aus.

[[t-webmaster]]
== Webmaster Team <webmaster@FreeBSD.org>

Das FreeBSD Webmaster-Team wird vom FreeBSD Documentation Engineering Team ernannt und ist dafür verantwortlich, die wichtigsten FreeBSD-Websites am Laufen zu halten.
Zu den Aufgaben dieses Teams gehören insbesondere die Konfiguration des Webservers und der CGI-Skripte sowie der Betrieb der Suchmaschinen für die Web-Site und die Mailing-Listen. Das Team kümmert sich um alle technischen Fragen, mit Ausnahme von Fehlern in der Dokumentation.

E-Mails an das Webmaster-Team werden derzeit an das Documentation Engineering Team weitergeleitet, und zusätzlich an:

* {wosch}

[[t-wiki]]
== Wiki Admin Team <wiki-admin@FreeBSD.org>

Das FreeBSD Wiki-Admin-Team ist dafür verantwortlich, die FreeBSD https://wiki.FreeBSD.org/[Wiki]-Site am Laufen zu halten. Sie sind auch das gesamte Design und die inhaltliche Struktur verantwortlich.

* {linimon}
* {koobs}
