---
title: "Die technischen Fortschritte von FreeBSD"
sidenav: about
---

= FreeBSD-Funktionen

== FreeBSD bietet viele hochentwickelte Funktionen.

Unabhängig von der Anwendung sollte ein Betriebssystem alle verfügbaren Ressourcen nutzen.
Der Fokus von FreeBSD liegt auf Leistung, Netzwerk- und Speichereffizienz kombiniert mit einfacher Verwaltung und umfassender Dokumentation, um das volle Potenzial eines Computers ausschöpfen zu können.

== Ein komplettes Betriebssystem auf Basis von 4.4BSD

Unter link:https://freebsdfoundation.org/freebsd/timeline/[Entwicklungsweg von FreeBSD] finden Sie die *BSD*-Software-Releases der Computer Systems Research Group an der University of California, Berkeley.
Jahrzehntelange Entwicklung hat zu fortschrittlicher Skalierbarkeit, Netzwerkleistung, Verwaltungstools, Unterstützung von Dateisystemen, Sicherheit und anderen Funktionen geführt.
FreeBSD ist im gesamten Internet in zentralen Router-Produkten zu finden, betreibt Root-Name-Server, hostet große Websites und bildet die Grundlage für weit verbreitete Desktop-Betriebssysteme.

[[features]]
== Eigenschaften

[[openzfs]]
=== OpenZFS

ZFS ist mehr als ein Dateisystem, es unterscheidet sich grundlegend von herkömmlichen Dateisystemen.
Durch die Kombination der traditionell getrennten Rollen von Software-RAID, Volume-Manager und Dateisystem bietet ZFS einzigartige Vorteile.

ZFS verfolgt drei Hauptziele bei der Entwicklung:

* Datenintegrität
* Gepoolter Speicher
* Leistung.

[[zfs-boot-environments]]
=== ZFS-Boot-Umgebungen
Eine ZFS-Boot-Umgebung ist ein bootfähiger Klon/Schnappschuss von speziell vorausgewählten Teilen eines Systems.

Zu den Anwendungsfällen gehören:

* Vollkommen sichere Upgrades/Änderungen am System
* Erstellen einer sicheren Fallback-ZFS-Boot-Umgebung vor Upgrades oder Änderungen am System
* Aktualisieren einer neuen (inaktiven) Umgebung, ohne die aktive Umgebung zu verändern
* Upgrade durchführen und die Ergebnisse innerhalb eines Jails testen
* Kopieren/Verschieben der ZFS-Boot-Umgebung auf einen anderen Rechner
* Größere Rekonfigurationen (Bareos/Postfix/...)
* Massenbelegung einer großen Anzahl von Servern mit einer konfigurierten BE
* Bare-Metal-Backup-Lösung.

[[jails]]
=== Jails

Jails haben ihren Ursprung in FreeBSD 4.X.

Sie bauen auf man:chroot[8] auf, das das Root-Verzeichnis ändert.
Dadurch entsteht eine sichere Umgebung, die vom Rest des Systems getrennt ist.
Prozesse, die in einer gesperrten Umgebung erstellt wurden, können nicht auf Dateien oder Ressourcen außerhalb der Umgebung zugreifen.

Jails verbessern chroot in mehrfacher Hinsicht.
In einer traditionellen Chroot-Umgebung sind Prozesse auf einen Teil des Dateisystems beschränkt.
Die restlichen Systemressourcen, Systembenutzer, laufenden Prozesse und das Netzwerksubsystem werden von den Chroot-Prozessen und den Prozessen des Host-Systems gemeinsam genutzt.
Jails schränken den Zugriff auf das Dateisystem, die Benutzergruppe und das Netzwerksubsystem weiter ein.
Es stehen feinere Zugriffskontrollen zur Verfügung.

[[ports-collection]]
=== Ports-Sammlung

Mehr als 30.000 Anwendungen und Bibliotheken sind auf FreeBSD link:https://www.freebsd.org/ports/[portiert] worden.
Die Architektur des Ports-Systems ermöglicht eine einfache Anpassung von Kompilierzeit-Optionen vieler Ports.

[[virtualization]]
=== Virtualisierung

link:https://bhyve.org/[bhyve] ist ein BSD-lizenzierter, legacy-freier Hypervisor, auf dem alle unterstützten Versionen von FreeBSD sowie andere Betriebssysteme laufen, die UEFI unterstützen, einschließlich, aber nicht beschränkt auf link:https://www.openbsd.org/[OpenBSD], link:https://www.microsoft.com/en-us/windows/[Windows(R)] und link:https://kernel.org/[Linux(R)], unter Verwendung von bhyve-firmware.

[[linuxulator]]
=== Linux-Binärkompatibilität

Die Linux-Binärkompatibilität, allgemein als link:https://wiki.freebsd.org/Linuxulator[Linuxulator] bezeichnet, ermöglicht es FreeBSD, viele unveränderte Linux-Binärdateien auszuführen.
Es handelt sich nicht um eine virtuelle Maschine oder Emulation.
Stattdessen stellt FreeBSD den Binärdateien Kernel-Schnittstellen zur Verfügung, die mit denen eines echten Linux-Kernels identisch sind.
Linuxulator ist vergleichbar mit der Ausführung von 32-Bit-FreeBSD-Binärdateien, die auf einem 64-Bit-FreeBSD-Kernel laufen.

[[dtrace]]
=== DTrace

DTrace, auch bekannt als Dynamic Tracing, wurde von Sun Microsystems(TM) entwickelt, um Leistungsengpässe in Produktions- und Vorproduktionssystemen zu lokalisieren.
Darüber hinaus kann DTrace dabei helfen, unerwartetes Verhalten im Kernel und im Userland zu untersuchen und zu debuggen.

DTrace verfügt über eine beeindruckende Reihe von Funktionen.
Es ist skriptfähig.
Entwickler können die DTrace-D-Programmiersprache verwenden, um Dienstprogramme für die benutzerdefinierte Profilerstellung zu erstellen.

Die FreeBSD-Implementierung bietet volle Unterstützung für DTrace im Kernel und experimentelle Unterstützung für DTrace im Userland.
Userland DTrace ermöglicht es dem Benutzer, mit Hilfe des pid-Providers Funktionsgrenzen von Userland-Programmen zu verfolgen und statische Sonden in Userland-Programme einzufügen, um sie später zu verfolgen.

[[capsicum]]
=== Capsicum
Capsicum ermöglicht das Sandboxing mehrerer Programme, die dann im "Capabilities-Modus" arbeiten, wie z.B.:

* tcpdump
* dhclient
* hast
* rwhod
* kdump.

[[vnet]]
=== Netzwerk-Virtualisierung

`VVNET` virtualisiert den Netzwerk-Stack.
Die Grundidee besteht darin, globale Ressourcen, insbesondere Variablen, in Ressourcen pro Netzwerk-Stack umzuwandeln und Funktionen, Sysctls, Eventhandler usw. die auf sie zugreifen im Kontext der richtigen Instanz handeln zu lassen.
Jeder (virtuelle) Netzwerk-Stack ist mit einem Jail verbunden, wobei vnet0 der uneingeschränkte Standard-Netzwerk-Stack des Basissystems ist.
Die `VIMAGE`-Funktionen können unabhängig davon verwendet werden, um vollständig virtualisierte Netzwerktopologien zu erstellen, und man:jail[8] kann direkt von einem vollständig virtualisierten Netzwerkstack profitieren.
