---
title: "Kontakt mit der FreeBSD-Gemeinschaft"
sidenav: about
---

include::shared/de/mailing-lists.adoc[]
include::shared/de/urls.adoc[]

= Kontakt zur FreeBSD-Gemeinschaft

link:../community/mailinglists[Mailinglisten sind der wichtigste Kommunikationskanal].

Bitte beachten Sie, dass Sie sich für einige Listen anmelden müssen, bevor Sie Beiträge schreiben können; Beiträge von Nicht-Abonnenten können in eine Warteschlange gestellt werden.

== Fragen zu FreeBSD

Schreiben Sie an die {freebsd-questions}; weitere Möglichkeiten finden Sie auf der Seite:../community[Community].

== Inhalt der Website

Fragen oder Vorschläge zur Dokumentation können an {freebsd-doc} gerichtet werden.

Alternativ gibt es für Inhalte des link:{main-site}[Dokumentations-Portals] - einschließlich des link:{handbook}[FreeBSD-Handbuchs] und der link:{faq}[FAQ] - die Möglichkeit, die Seite in GitHub zu bearbeiten.

== link:../administration/[FreeBSD Projektverwaltung und Management]

Webmaster-Team, Sicherheits-Team, Postmaster-Team, Bugmeisters und andere.

== Sonstiges

link:../commercial/[Kommerzielle Anbieter]

- http://www.freebsdmall.com/[The FreeBSD Mall] ist ein Anbieter von hochwertiger FreeBSD-Software, Dokumentation, Support und Dienstleistungen.
