---
title: "Core Team Geschäftsordnung"
sidenav: docs
---

= Core Team Geschäftsordnung

Diese Statuten wurden am 28. August 2000 durch eine Abstimmung der aktiven Committer angenommen.

* Aktive Committer haben in den letzten 12 Monaten einen Commit in den Tree gemacht.
* Der Kern besteht aus 9 gewählten aktiven Committern.
* Core-Wahlen werden alle 2 Jahre abgehalten, das erste Mal im September 2000.
* Core-Mitglieder und Committer können durch eine 2/3 Abstimmung des Core Teams ausgeschlossen werden.
* Fällt die Größe des Core Teams unter 7, wird eine vorgezogene Wahl abgehalten.
* Eine Petition von 1/3 der aktiven Committer kann eine vorgezogene Wahl auslösen.
* Alle Wahlen werden wie folgt durchgeführt:
** Das Core Team ernennt und verkündet jemanden, der die Wahl leitet.
** 1 Woche, um die aktiven Committer zu zählen, die für das Core Team kandidieren wollen.
** 4 Wochen für die eigentliche Wahl.
** 1 Woche zum Auszählen und Veröffentlichen der Ergebnisse.
** Jeder aktive Committer kann einmal für bis zu neun Kandidaten stimmen.
** Das neue Core Team tritt 1 Woche nach Veröffentlichung der Ergebnisse in Kraft.
** Unentschiedene Stimmen werden von eindeutig gewählten neuen Core Team-Mitgliedern entschieden.
* Diese Regeln können mit einer 2/3 Mehrheit der Committer geändert werden, wenn mindestens 50% der aktiven Committer ihre Stimme abgeben.

== Zusätzliche Informationen

Die letzte Core Team-Wahl wurde im Mai 2022 abgehalten. Die nächste Wahl ist für Mai/Juni 2024 geplant.

== Core Team-Auslegungen der Geschäftsordnung

Das Core Team wird von Zeit zu Zeit Interpretationen der Statuten herausgeben, wenn dies notwendig ist, um Bereiche zu klären, die in den Statuten zweideutig sein könnten, und um den reibungslosen Betrieb des Projekts zu gewährleisten.

* *20020503* Die nächste Wahl findet immer zwei Jahre nach der vorangegangenen Wahl statt.
Das bedeutet, dass bei vorgezogenen Wahlen der Termin für die nächste Wahl so festgelegt wird, dass sie zwei Jahre nach der vorgezogenen Wahl stattfindet.

link:../developer[Ressourcen für FreeBSD-Committer]
