---
title: "Vorschlagen von Committern"
sidenav: docs
---

= Vorschlagen von Committern

Die folgenden Hinweise sollen potentiellen Mentoren bei der Entscheidung helfen, ob ein Kandidat für ein Commit-Bit geeignet ist, und bei der Vorbereitung eines Vorschlags für ein Commit-Bit zur Prüfung durch das Core Team oder seine Delegierten. Beachten Sie, dass im Falle einer delegierten Genehmigung (z.B. an Portmgr oder Doceng), zusätzliche Verfahren oder Einschränkungen gelten können (z.B. für die Art des Beitrags).

Die Prüfer von Commit-Bit-Anträgen werden bei potenziellen Entwicklern nach einigen wichtigen Eigenschaften Ausschau halten: starke technische Fähigkeiten, eine Erfolgsbilanz von Beiträgen zum FreeBSD-Projekt, Beweise für die Fähigkeit, unabhängig innerhalb der Gemeinschaft zu arbeiten (d.h., dass die Betreuung nicht unbegrenzt fortgesetzt werden muss), Beweise für die Fähigkeit eines Entwicklers, sich konstruktiv mit der FreeBSD-Gemeinschaft auseinanderzusetzen (und insbesondere die sozialen Fähigkeiten zu besitzen, um gelegentlich hitzige Online-Diskussionen zu führen), und eine Verpflichtung, in Zukunft zum Projekt beizutragen. Die Unterlagen für einen Commit-Bit-Vorschlag enthalten in der Regel eine Beschreibung des Hintergrunds und der Ausbildung des Kandidaten, den Kontext seiner Beiträge zum Projekt (z.B. als Freiwilliger, Angestellter usw.), Verweise auf Patches/PRs/Commits, die seine Beitragsbilanz rechtfertigen, Hinweise auf die Teilnahme an Mailinglisten oder andere Aktivitäten in der Gemeinschaft (z.B. Präsentationen auf BSD-Konferenzen), einen deutlichen Hinweis auf die bisherige konstruktive Zusammenarbeit mit dem Mentor sowie eine Liste von Interessen und potenziellen Bereichen, in denen er weiterhin und in Zukunft Beiträge leisten möchte.

Potenzielle Mentoren werden daran erinnert, dass es weitaus einfacher ist, den Zugang zu einem Projekt zu gewähren, als ihn zu entziehen, und dass daher konstruktiver Interaktion mit der Gemeinschaft mehr Bedeutung beigemessen wird als rein technischen Beiträgen. Wenn ein Mentor unsicher ist, ob ein Kandidat geeignet ist, kann es sinnvoll sein, sich zunächst mit einer informellen Anfrage an das Core Team zu wenden, anstatt einen formellen Vorschlag einzureichen - dies könnte dazu führen, dass man ihm rät, fortzufahren, weiteres unterstützendes Material anzufordern oder vorzuschlagen, dass ein Vorschlag zurückgestellt werden sollte, während man weitere Erfahrungen sammelt. Es wird gehofft, dass Anfragen, weitere Erfahrungen zu sammeln oder zusätzliche Beweise für die Teilnahme und den Beitrag der Gemeinschaft zu erbringen, in dem Sinne angenommen werden, in dem sie gemeint sind: Die Gewährung eines Commit-Bits ist eine bedeutende Maßnahme und basiert zu einem großen Teil auf der geleisteten Arbeit und nicht nur auf starken technischen Fähigkeiten. Das Projekt würde lieber einen konservativen Ansatz bei der Vergabe von Commit-Rechten wählen, als sie voreilig zu vergeben.

In einigen Fällen können "Vendor Commit Bits" gewährt werden, um direkte Commits für Gerätetreiber (oder möglicherweise andere Komponenten) zu ermöglichen, die z.B. von einem Gerätehersteller gepflegt werden. Diese können an einen niedrigeren Standard der früheren Beteiligung der Gemeinschaft gebunden sein, basierend auf einem starken Engagement des Herstellers und eines erfahrenen Mentors, sowie einer begrenzten Befugnis, Änderungen im System unabhängig vorzunehmen. Es ist äußerst wichtig, dass solche Commit Bits mit angemessener Diskretion und im Bewusstsein der Bedenken der Gemeinschaft verwendet werden; es liegt in der Verantwortung des Mentors sicherzustellen, dass keine unerwünschten Spannungen entstehen und dass die Änderungen mit den Projektverfahren und den Erwartungen der Gemeinschaft übereinstimmen. Wenn ein Commit-Bit in diesem Zusammenhang gewährt wird, kann es widerrufen werden, wenn die Person ihren Arbeitgeber verlässt; es gibt jedoch auch eine beträchtliche Anzahl von Personen mit "Vendor Commit Bits", die umfassendere Beiträge leisten, und dies ist das erhoffte Ergebnis! Mentoren, die Vendor Commit Bits vorschlagen, sollten alle notwendigen Schritte unternehmen, um sicherzustellen, dass Commit Bits nur an Personen vergeben werden, die die Verantwortung für die Qualität und das Testen der Beiträge, die sie im Namen des Anbieters leisten, übernehmen können, und die über die notwendigen technischen und sozialen Fähigkeiten verfügen, um konstruktiv mit der Gemeinschaft zusammenzuarbeiten. Es wird empfohlen, dass Vorschläge für solche Bits weitestgehend den gleichen Inhalt haben, wie er von normalen Commit Bits erwartet wird, mit besonderem Augenmerk auf die Qualität des technischen Beitrags.
