---
title: "Arbeiten mit Hüten"
sidenav: docs
---

include::shared/authors.adoc[]

= Arbeiten mit Hüten

{imp-name}, Mitglied des Core Teams zum Zeitpunkt des Schreibens der folgenden Zeilen, weist auf die folgenden Überlegungen und Praktiken bei der Arbeit mit Hüten (Verantwortlichen für Teile des Source-Baums) hin:

Dies ist keine offizielle Erklärung des Core Teams, sondern eher die persönliche Interpretation der Position des Core Teams durch ein Core Team-Mitglieds, sowohl als amtierendes Mitglied des Core Teams als auch als ehemaliger Sicherheitsbeauftragter. Dies ist nur ein Leitfaden, kein Knüppel für Beschwerden. Ähnlich wie style(9) ein Leitfaden für den Quellcode ist, ist dieses Dokument nicht als absolute Zwangsjacke gedacht.

Wenn das Core Team jemanden zu einem "Hut" ernennt, erwartet es, dass diese Person für einen Bereich des Quellcode-Baums verantwortlich ist. Das Core Team erwartet, dass diese Person die endgültige Autorität in diesem Bereich des Baumes ist, oder dass sie über genügend Selbsterkenntnis verfügt, um zu wissen, dass sie es nicht ist und sich qualifizierte Hilfe sucht. Das Core Team erwartet von dieser Person, dass sie die Entwicklung in diesem Bereich des Baumes leitet. Manchmal bedeutet dies, eine pro-aktive Rolle in den täglichen Angelegenheiten zu übernehmen, während es manchmal bedeutet, eine reaktive Rolle bei der Überprüfung des übergebenen Codes zu übernehmen.

Wenn Leute Patches einreichen, die sich möglicherweise auf diesen Bereich des Baums auswirken, erwartet das Core Team, dass der Hut oder seine ernannten Stellvertreter die Patches entsprechend überprüfen. Das Core Team erwartet, dass der Hut mit dem Einreicher des Patches zusammenarbeitet, um eventuelle Probleme zu beheben, die mit den Patches verbunden sind. Das Core Team erwartet, dass der Hut Lösungen anbietet und mit dem Einsender zusammenarbeitet, um einen Kompromiss zu finden. Das Core Team erwartet, dass der Hut höflich ist. Es ist angemessen, dass die Hüte verlangen, dass die normalen Projektregeln bei der Überprüfung von Patches befolgt werden (z.B. dass sie im Allgemeinen mit style(9) oder dem vorherrschenden Stil der Datei übereinstimmen, dass Stil- und Inhaltsänderungen getrennt werden).

Wenn ein Streitfall auftritt, erwartet das Core Team, dass der Hut sich nach Kräften bemüht, einen Kompromiss zu finden oder den Streit anderweitig beizulegen. Von dem Hut wird erwartet, dass er sich gegenüber allen beteiligten Parteien höflich verhält. In extremen Fällen erkennt das Core Team an, dass die Hüte einen großen Knüppel schwingen und sagen müssen: "Nein, das ist nicht akzeptabel und kann nicht committed werden (oder muss rückgängig gemacht werden)". Das Core Team sieht diese Möglichkeit als letztes Mittel an und würde es missbilligen, wenn Hüte dies entweder zu oft oder als erste Reaktion anwenden würden.

Oft beeinträchtigt das wirkliche Leben die Fähigkeit eines Hutes, seine Aufgaben zu erfüllen. Eine Bedingung, die das Core Team den Hüten der Welt im Allgemeinen auferlegt, ist, dass sie einen Stellvertreter haben, der in ihrer Abwesenheit handeln kann. Von diesem Stellvertreter wird erwartet, dass er ein aktiver Teilnehmer des Teams ist, das der Hut zusammenstellt, und dass er mit allen Problemen vertraut ist, die den Teil des Baums betreffen, den der Hut leitet. Vom Stellvertreter wird erwartet, dass er in der Lage ist, in Abwesenheit des Huts zu handeln. Die Stellvertreter des Sicherheitsbeauftragten geben zum Beispiel Sicherheitshinweise aus, wenn der SO nicht anwesend ist. In extremen Fällen kann der Stellvertreter eine Angelegenheit aufschieben, bis der Hut zurückkehrt, aber das dürfte eher die Ausnahme als die Regel sein, vor allem, wenn die Rückkehr des Huts weit in der Zukunft liegt.

Die Hüte sind dem Core Team verantwortlich. Wenn sie gute Arbeit leisten, wird das Core Team sie in Ruhe lassen. Wenn sie schlechte Arbeit leisten, hat das Core Team die Möglichkeit, sie zu entfernen. Von Hüten wird erwartet, dass sie mit dem Core Team zusammenarbeiten, wenn dieser Probleme mit der Erfüllung ihrer Aufgaben hat. Sie dienen nach dem Willen des Core Teams.

Das Core Team wird manchmal zusätzliche, spezifische Anforderungen für einen bestimmten Hut auferlegen, die nicht für alle Hüte gelten. Diese Bedingungen können sich mit der Zeit ändern.

Von Committern und anderen, die mit Hüten zusammenarbeiten, wird erwartet, dass sie ihren gesunden Menschenverstand einsetzen und höflich zu den Hüten sind. Von ihnen wird erwartet, dass sie mit dem Hut und seinem Team zusammenarbeiten, um eine für alle akzeptable Lösung zu finden. Falls kein Kompromiss erzielt werden kann, wird von den Committern erwartet, dass sie die Entscheidungen des Hüten mit Wohlwollen akzeptieren. In Ausnahmefällen können diese Entscheidungen beim Core Team angefochten werden. Das Core Team wird jedoch im Allgemeinen die Entscheidungen der von ihm ernannten Hüten nicht außer Kraft setzen, es sei denn, der Hut hat in böser Absicht oder willkürlich gehandelt. Das Core Team ist kein technischer Prüfungsausschuss und hat die Hüte als Mini-TRBs (Technical Review Boards) eingerichtet, um der Streitbeilegung einen angemessenen Rahmen zu geben.

Wenn ein Committer das Gefühl hat, dass ein Hut seine Macht missbraucht oder regelmäßig unhöflich zu Mitwirkenden ist, dann sollte er die Angelegenheit an das Core Team herantragen. Das Problem kann technischer, sozialer oder verfahrenstechnischer Natur sein, oder eine Kombination oder Untermenge davon. Das Core Team wird sich den Fall anhören und eine Entscheidung treffen und erwartet von beiden Seiten, dass sie sich an diese Entscheidung halten. Das Core Team schätzt spezifische Beschwerden mehr als allgemeine, da diese leichter zu lösen sind.

Das Core Team erwartet von den Committern, dass sie in den entsprechenden Mailinglisten zusammenarbeiten, um ihre Probleme zu lösen. Der Hut und sein Team sollten relativ selten in ihrer Rolle als Hut involviert sein, und stattdessen normalerweise nur ein weiterer Committer sein. (Die einzige Ausnahme ist der Hut des Sicherheitsbeauftragten, der heimlich Schwachstellen lösen muss, bevor sie bekannt gegeben werden). Der Hut sollte ein "Erster unter Gleichen" sein, nicht ein Vorsitzender.
