---
title: "Gemeinschaft"
sidenav: community
---

include::shared/de/urls.adoc[]

= Gemeinschaft

Die FreeBSD-Gemeinschaft ist vielfältig und umfangreich und kann überall dort gefunden werden, wo großartige Unterhaltungen und Aktivitäten stattfinden.
Sie werden feststellen, dass unsere Gemeinschaft und ihre Foren intelligent, einladend und zugänglich sind.

Das Projekt unterhält mehrere offizielle Community-Foren, in denen Entwickler, Mitwirkende und Benutzer Hilfe und Unterstützung finden, sich auf dem Laufenden halten, koordinieren und zusammenarbeiten oder sich einfach nur zurücklehnen, entspannen und Kontakte knüpfen können.

Wenn Sie asynchrone und langlebige Kommunikationskanäle bevorzugen, bietet FreeBSD über hundert https://lists.freebsd.org[Mailinglisten], die ein breites Spektrum an Themen abdecken, sowie webbasierte https://forums.freebsd.org/[Foren] und mehrere Usenet link:{handbook}eresources/#eresources-news[News-Groups].

Für die Zusammenarbeit in Echtzeit haben wir eine Reihe von https://wiki.freebsd.org/IRC/[FreeBSD IRC-Kanälen] und eine Instanz auf https://wiki.freebsd.org/Discord[Discord], wo Sie Unterstützung finden, lernen können, mitzuarbeiten, Live-Streams anschauen können und vieles mehr.

Wenn Sie an beruflicher Entwicklung und Networking interessiert sind, folgen Sie uns auf https://www.linkedin.com/company/freebsd/[LinkedIn] und treten Sie unserer offiziellen https://www.linkedin.com/groups/47628[FreeBSD LinkedIn Group] bei.

Für regelmäßig stattfindende persönliche und Online-Treffen sollten Sie einen Blick auf unsere https://www.freebsd.org/events[FreeBSD Veranstaltungen] werfen, wo wir einen Feed und einen Kalender mit anstehenden Veranstaltungen führen.
Im vergangenen Jahr gab es {{< get-event-last-year-info "events" >}} Veranstaltungen auf der ganzen Welt.
////
Letztes Jahr gab es {{< get-event-last-year-info "events" >}} Veranstaltungen in {{< get-event-last-year-info "countries" >}} verschiedenen Ländern rund um die Welt.
////

Auf Twitter können Sie https://twitter.com/freebsd[@freebsd], https://twitter.com/freebsdhelp[@freebsdhelp], oder https://twitter.com/freebsdcore[@freebsdcore] folgen.

Auf Reddit finden Sie den Link zur FreeBSD-Gemeinschaft: https://www.reddit.com/r/freebsd/[hier].

Neben den offiziell betriebenen Community-Bereichen gibt es https://www.freebsd.org/usergroups/[User Groups] in {{< get-usergroups-info "countries" >}} Ländern sowie sehr aktive FreeBSD-Communities auf https://twitter.com/search?q=freebsd[Twitter], https://stackoverflow.com/questions/tagged/freebsd[StackOverflow], https://serverfault.com/questions/tagged/freebsd[ServerFault] und https://www.meetup.com/topics/freebsd/[MeetUp.com], neben vielen anderen technologiebezogenen Bereichen.

Das https://wiki.freebsd.org/[FreeBSD Wiki] enthält Informationen über die Entwicklung und verwandte Projekte.

== Video-Inhalte

Auf YouTube gibt es einen offiziellen link:https://www.youtube.com/FreeBSDProject[FreeBSD]-Kanal mit Entwickler-Gipfeltreffen und "Sprechstunden" sowie einen link:https://www.youtube.com/bsdconferences[BSD Conferences]-Kanal mit aufgezeichneten Präsentationen von technischen FreeBSD-Konferenzen.
