---
title: "FreeBSD State of the Union, 1999"
sidenav: about
loadNews: false
---

= FreeBSD State of the Union, 1999

_Von Jordan Hubbard <jkh@FreeBSD.ORG>, Sonntag, 10. Januar 1999._

Nun, ein weiteres Jahr liegt hinter uns, Leute, und es ist wahrscheinlich höchste Zeit für einen weiteren Bericht zur Lage der Union!

Ähem... Ich bin mir nie ganz sicher, wie ich diese Dinge formulieren soll, da ich immer an einen US-Präsidenten denke, der vor dem Kamin sitzt und versucht, für die Mais anbauenden Staaten bodenständig und volkstümlich zu klingen, oder vielleicht an die englische Königin am Weihnachtstag, die ihre übliche düstere und doch hoffnungsvolle Ansprache darüber hält, wie die Dinge für Britannia im vergangenen Jahr gelaufen sind und worüber jeder vielleicht für das nächste Jahr nachdenken sollte. Beides trifft im Grunde genommen nicht auf mich zu, also werde ich mich vielleicht auf den Punkt bringen und mich auf die wichtigsten Lehren (und Ziele) konzentrieren, die sich für mich aus dem Jahr 1998 ergeben haben.

1998 war natürlich das Jahr, in dem das Internet größer wurde (keine Überraschung), verschiedene "Internetpraneure" (Gag) reicher wurden und die FreeBSD-Benutzerbasis, gemessen an den FTP-Download-Statistiken, mit der üblichen Rate von 200-300% wuchs. Weitere Unternehmen traten in die FreeBSD-Arena ein und boten entweder Erweiterungen oder Lösungen für FreeBSD an, und unsere PR-Maschinerie, so schwach und unauffällig sie oft ist, schaffte es, die Dinge weiter voranzutreiben. Alles in allem war es ein sehr gutes Jahr für FreeBSD, und ich glaube nicht, dass selbst die paranoidesten unter uns etwas anderes behaupten könnten - Microsoft hat einen auf den Deckel gekriegt, wir sind größer und ein bisschen bekannter geworden, das Leben war gut.

Nun, meistens. Wenn ich meine rosarote Brille für eine Sekunde abnehme, kann ich auch sagen, dass es immer noch eine Reihe von Steinen auf der Straße und unerwartete Kurven gab, die uns nicht immer die beste Kontrolle gaben. Während die Downloads gestiegen sind, haben die CD-Verkäufe nicht ganz so stark zugelegt, da der gesamte CD-Markt im Allgemeinen unter der zunehmenden Verfügbarkeit des Internets und der damit verbundenen Aushöhlung einiger grundlegender Vorteile der CD leidet. Es wäre jedoch töricht, sich weiterhin auf ein einziges CD-Produkt zu verlassen, um die Art von Subventionen zu erhalten, die das Projekt stetig vorangebracht haben (wir haben zum Beispiel die Größe des FreeBSD.org Computing Clusters mehr als verdoppelt und unser Förderprogramm für Entwickler im Jahr 1998 erheblich erweitert, alles Dinge, die $$$ kosten). Es ist ziemlich offensichtlich, daß Walnut Creek CDROM die Anzahl der angebotenen Produkte erhöhen muß, wenn es ein effektiver Akteur im FreeBSD-Spiel bleiben will, und wir müssen als Projekt weiterhin flexibel sein, um alle Arten von Beziehungen mit denjenigen zu erkunden, die jetzt ein berechtigtes Interesse am Erfolg von FreeBSD haben könnten. Die Dinge sind weit über den Punkt hinaus, an dem wir alles, was als ernsthafte und "erwachsene" Lösung getan werden muss, allein durch guten Willen und Freiwilligkeit erreichen können.

Aus diesem Grund wurden Websites wie http://www.freebsdmall.com[FreeBSD Mall] eingerichtet, um eine größere Auswahl an FreeBSD-bezogenen Produkten zu vermarkten. Außerdem haben wir damit begonnen, Beziehungen zu verschiedenen Unternehmen zu knüpfen, die einen messbaren Nutzen aus einer PR-Kampagne ziehen können, die den Ruf von FreeBSD stärkt (übersetzt: wir wollen, dass sie dafür bezahlen :). Wie viele Leute bereits bitter festgestellt haben, ist dieses Geschäft eine Gleichung aus 10% Technologie und 90% Wahrnehmung, was die Richtung angeht, in die die Leute rennen, und so sehr man sie auch für die hirnlosen Schäfchen hasst, die sie sind, so muss man doch die Tendenzen und Verhaltensmuster der Leute verstehen, wenn es darum geht, mit etwas umzugehen, das sie nicht wirklich verstehen. Bei der Technologie haben wir wirklich gute Arbeit geleistet (und darauf sollten wir stolz sein), aber allzu oft werfen wir die Hände in den Schoß, wenn es um die Wahrnehmung geht, und sagen den Leuten, sie sollen denken, was sie wollen. Schlechte Techniker! Kurzsichtige Techniker! :-)

Was können wir tun, um dies im Jahr 1999 zu ändern? Nun, ich habe auch gehört, wie unsere Befürworter nach logistischer Unterstützung riefen ("Backup! Wir brauchen hier ein _Backup_!"), und ich habe ihnen zugehört. Ein Teil meines Projekts für das neue Jahr besteht darin, mehr digitale Daemon-Bilder zur Verfügung zu stellen (die ich bereits in Auftrag gegeben habe), mehr Glossen mit verschiedenen praktischen Vergleichstabellen ("FreeBSD und NT", "FreeBSD und Solaris", "FreeBSD und Linux" usw.) und mehr Newsletter zum Verteilen an die Leute. Wir können auch mehr Marketingartikel wie Buttons, Aufkleber, neue T-Shirts usw. produzieren, um den Leuten eine breitere Palette von Dingen zu geben, auf die sie stolz zeigen können, um das "aufkommende FreeBSD-Phänomen" zu unterstützen. Wenn es uns gelingt, mehr Geld für die PR zu sammeln, können wir vielleicht auch einige dieser Gegenstände in großen Mengen kaufen, um sie als Werbegeschenke zu verwenden. Ansonsten bin ich immer offen für Vorschläge. Wir brauchen eine effektivere PR, das ist unbestritten, es geht nur darum, unsere Ziele so zu wählen, dass sie bei einem begrenzten Betriebsbudget maximale Wirkung erzielen.

== Das Kernteam:

Das Jahr 1998 endete auch für das FreeBSD-Projektmanagement mit einem Paukenschlag: Ein größtenteils in sich gekehrtes Kernteam stachelte ein paar bärtige dänische Wikinger dazu an, eine nächtliche Razzia auf -current zu veranstalten und die schwachen und lahmen Teile des Quellcodes rücksichtslos auszumerzen. Unglücklicherweise waren einige dieser schwachen oder lahmen Teile des Codes zu diesem Zeitpunkt noch in Gebrauch, und da es keine öffentliche Vorwarnung gegeben hatte, hinterließ es bei den verschiedenen Anhängern von -current nicht gerade das Gefühl, dass dieses Ereignis der Höhepunkt ihrer Weihnachtszeit sein würde. Ihre Beschwerden führten wiederum zu einer Art Verfassungskrise innerhalb des Kerns, wobei sich die rivalisierenden Fraktionen gegenseitig beschuldigten, entweder den Fortschritt zu behindern oder diesen mit Cowboytaktiken zu erreichen, und jede Fraktion hatte ihre berechtigten Punkte ebenso wie ihre völlig unvernünftigen. Daraufhin wurden verschiedene Vorschläge gemacht, wie wir ein "besseres Kernteam" zusammenstellen könnten, zu dem solche Dinge einfach nicht passierten (oder, falls doch, wäre es nicht unsere Schuld, da wir alle schon lange weg wären :-), und viele dieser vorgeschlagenen Heilmittel wurden schließlich, völlig zu Recht, als schlimmer als die Krankheit angesehen. Was haben wir also aus dieser Übung gelernt?

Zunächst einmal sind sich jetzt wohl alle einig, dass diese Art von Schießereien aus dem fahrenden Auto heraus einfach keine Option für die Zukunft sind, ganz gleich, wie sie begründet werden. Jeder, der eine größere Hinzufügung oder Entfernung von Funktionalität aus dem Quellcode-Baum in Erwägung zieht, MUSS diese Absichten lange im Voraus kommunizieren und der Leserschaft von -current, -stable oder -announce (die beiden ersteren abhängig von dem Zweig, den die Änderungen betreffen und die letzteren vom Ausmaß der Änderungen) ausreichend Zeit geben, um zu reagieren. Wenn es eine eindeutig negative Reaktion auf eine vorgeschlagene Änderung gibt, wird sie erst dann umgesetzt, wenn es dem Vorschlag irgendwie gelingt, die Leute durch überzeugende Argumente für sich zu gewinnen. Wenn die Reaktionen eher gemischt sind oder es überhaupt keine Reaktionen gibt, kann der Projektträger nach eigenem Ermessen vorgehen, jedoch niemals ohne vorherige Ankündigung.

Zweitens möchte ich als Reaktion auf die verschiedenen Vorschläge, die Kerngruppe entweder zu entkernen oder die Kerngruppe per Volksabstimmung wählen zu lassen, sagen, dass wir das nicht tun werden. Es gibt wahrscheinlich mehrere Leute im Kernteam, die gerne zurücktreten und sich zurückziehen würden, wenn sie das Gefühl haben, dass ein angemessener Ersatz gefunden wurde und das Projekt in guten Händen ist, aber niemand von uns mag das Szenario, dass jemand offen aus dem Kernteam herausgedrängt wird. Das ist einfach kein vernünftiger Weg, wenn es so viele weniger schmerzhafte Alternativen gibt, und ich für meinen Teil würde es vorziehen, den Kern einfach wachsen zu lassen und die inaktiven Mitglieder fallen zu lassen, wenn sie selbst zu der Entscheidung gekommen sind, dass sie nichts mehr auf "Kern-Ebene" beizutragen haben, wobei der Austritt aus dem Kern einige Leute nicht davon abgehalten hat, als effektive Committer zu bleiben oder andere wertvolle Beiträge zu leisten.

Wir sind ein freies Software-Projekt und niemand wird dafür bezahlt, zum Kern zu gehören, egal wie ernst wir manchmal versucht sein mögen, die ganze Kern-Sache zu nehmen, und wir müssen uns daran erinnern, dass all dies als ein Haufen von Leuten begann, die einfach zusammenarbeiten wollten, um etwas Nützliches und Interessantes zu schaffen. An dem Tag, an dem wir diese informelle Atmosphäre der Produktivität über die Politik stellen, geht etwas sehr Grundlegendes im Zentrum von Core verloren, und das ist auch der Tag, an dem ich mich selbst zurückziehe, meinen Hut an einen Nachfolger übergebe und allen viel Glück wünsche.

Ich kann auch nur eine ähnliche Warnung aussprechen, was die Idee angeht, den Core aus der Benutzerbasis zu wählen, oder mit Committern, die als eine Art "Wahlkollegium" dienen, so schön und demokratisch das auch klingen mag. Das FreeBSD-Core-Team ist kein demokratisch gewähltes Gremium und wurde in der Tat sehr sorgfältig auf eine nicht-demokratische Weise zusammengestellt. Wir haben das Core-Team mit der Absicht zusammengestellt, so viele FreeBSD-Evangelisten und -Entwickler zu finden, wie wir nur konnten, und wir haben immer wieder Leute nach den gleichen Kriterien hinzugefügt.

Wenn wir jemanden in den Core aufnehmen, achten wir nicht darauf, ob er in letzter Zeit Beliebtheitswettbewerbe gewonnen hat oder dreimal hintereinander die Programmierolympiade gewonnen hat, sondern wir fragen uns: "Bringt diese Person ein einzigartiges Talent oder eine besondere Sichtweise in die Gruppe ein? Wird das resultierende Ganze größer sein als die Summe seiner Teile?" Dies sind unsere beiden wichtigsten Anliegen und in der Tat die einzigen Gründe, aus denen wir es jemals für nötig befunden haben, den Austritt einer Person aus dem Kernteam zu fordern. Wir können einiges von Leuten tolerieren, aber nicht, wenn es die grundlegende Fähigkeit des Kerns zur Zusammenarbeit beeinträchtigt oder versucht, die Meinungsvielfalt zu untergraben, die wir so hart kultiviert haben. Es ist gut, als Kernteam eine effektive Gruppe von Entscheidungsträgern zu sein, und wir haben unsere Momente (in beide Richtungen), aber manchmal ist es noch besser zu wissen, wann man sich einfach aus dem Weg gehen und einfach nur zuhören sollte.

Core arbeitet auch weiterhin an der Ausarbeitung einiger interner Dokumente, die viel detaillierter beschreiben, was unsere Regeln als Committer sind, die jegliche "Core-Mitglieder-Privilegien" ersetzen und regeln, wie groß angelegte Code-Entfernungen und Hinzufügungen durchgeführt werden sollten. Wir werden den Committern etwas zukommen lassen, sobald wir es zu unserer beiderseitigen Zufriedenheit ausgearbeitet haben, aber kurz gesagt geht es im Grunde nur darum, dass die Leute gewarnt werden müssen, bevor solche Änderungen vorgenommen werden, und dass der Eigentümer eines bestimmten Codeteils das erste Wort darüber haben sollte, ob es an der Zeit ist, ihn im Namen von Veralterung oder Redundanz zu löschen. Schließlich befassen wir uns mit der allgemeinen Frage der Kommunikation innerhalb und außerhalb des Kerns und mit der Frage, ob wir zum jetzigen Zeitpunkt neue Mitglieder aufnehmen sollten oder nicht. Diese Diskussion ist noch nicht abgeschlossen, und ich werde mein Bestes tun, um alle auf dem Laufenden zu halten, wenn die Dinge voranschreiten.

== Versionsnummerierung:

Andere Entscheidungen, die anstehen, betreffen die Rückkehr zu unserer früheren Praxis, "Major"-Versionsnummern für Zweige und "Minor"-Nummern für Versionen zu verwenden, wobei das Feld für die Revisionsnummer nur dazu verwendet wird, um Punktversionen zu kennzeichnen, die aus irgendeinem Grund gemacht wurden, der bedeutend genug war, um eine solche spezielle Version zu verdienen. Das bedeutet, dass die nächste Version 3.1 und nicht 3.0.1 heißen wird, und der neue Zweig wird 4.0-aktuell und nicht 3.1-aktuell sein. Ist dies nur ein Marketing-Trick? Nein, das ist es nicht, obwohl das Marketing tatsächlich ein häufiges Opfer unseres derzeitigen Nummerierungsschemas war.

Wir haben häufig ziemlich große Änderungen zwischen unseren "Point-Releases" vorgenommen, Sprünge wie 2.2.5->2.2.6 und 2.2.6->2.2.7 waren viel größer als die meisten Leute ihnen zugetraut haben, da es sich nur um eine kleine Revisionsnummer handelte. Diese einfache Facette der menschlichen Natur reduzierte die Effektivität dieser Veröffentlichungen und unterschätzte die Arbeit, die unsere Entwickler leisten, um _jede_ Veröffentlichung wesentlich zu verbessern, unabhängig davon, auf welchem Zweig sie sich befindet.

Dies ist kein Trend, der sich umzukehren scheint, und so fühle ich mich ziemlich sicher, wenn ich sage, dass 3.1 eine "Vollversion" gegenüber 3.0 sein wird, und nicht nur die "3.0.1", die einen so unterschiedlichen Eindruck vermittelt. Es ist auch sehr wichtig anzumerken, dass, da unsere Zweige heutzutage in der Regel 12-18 Monate dauern, egal was wir versuchen, um einen Zweig früher zu beenden, ein großer Versionssprung (4.0) völlig verdient ist für etwas, das den Status einer Vollversion nicht vor irgendwann im Jahr 2000 erreichen wird. Das wird die Marketingleute glücklich machen, da sie nicht mehr so einen harten Kampf um die Wahrnehmung der Zahlen führen müssen, und es wird die Benutzer glücklich machen, da sie ein klareres Bild davon bekommen, was sich z.B. von 3.1 zu 3.2 im Vergleich zu 3.1 zu 3.1.1 geändert hat (was ein wichtiges Sicherheitsupdate sein könnte). Es wird auch diesen speziellen Entwickler glücklich machen, da ich den Platz für die Revisionsnummer wieder zurückbekomme, um Punktversionen zu erstellen. Es ist ein Gewinn und deshalb werden wir es tun. 3.0.1 ist tot, lang lebe 3.1! :)

== Technologie:

Im letzten Jahr gab es auch einen erfolgreichen Übergang zum ELF- statt zum a.out-Format und ein neues Kernel-Loadable-Module-Schema, das das Einlesen von Modulen ohne eine Laufzeitabhängigkeit von /usr/bin/ld ermöglicht. Wir haben auch einen neuen Bootloader (mit einem vierten Interpreter!), der beim Booten einen "Kernel" zusammenstellt. Dies sind beides mächtige neue Mechanismen, die uns zusammen mit einigen neuen Dingen, die 1999 kommen werden, ein viel dynamischeres und erweiterbares System geben sollten, als wir es je zuvor hatten.

Nicht zu vernachlässigen ist auch unser neues SCSI-CAM-System, das uns ein robusteres Verhalten bei großen Laufwerksanordnungen ermöglicht und mehr High-End-SCSI-Controller unterstützt, oder die Unterstützung für mehrere Prozessoren auf dem x86. Mit der Veröffentlichung von 3.0 haben wir in allen Bereichen beträchtliche Fortschritte gemacht und mit der Portierung auf die DEC-Alpha-Architektur endlich einen Punkt erreicht, an dem sich die Leute mehr Gedanken über die Paketsammlung als über funktionierende Kernel oder ein /usr/src, das gebaut wurde, gemacht haben. Das ist ein beträchtlicher Fortschritt in Richtung "echter Nützlichkeit" und ich hoffe, dass 1999 eine vollständig desktopfähige Version von FreeBSD/axp erscheinen wird (ganz zu schweigen von einer serverfähigen), wobei verschiedene Schwierigkeiten mit der X-Server-Technologie den Alpha-Desktop zu einem einzigartigen Meilenstein machen, besonders wenn er auf einer ARC- oder AlphaBIOS-Maschine läuft. 1999 könnte auch die frühe Veröffentlichung einer SPARC-Portierung erfolgen, obwohl es noch viel zu früh ist, um etwas Definitives zu sagen. Melden Sie sich bei der sparc@FreeBSD.org Mailingliste an, wenn Sie diese Bemühungen verfolgen wollen.

IPv6 und IPSec waren 1998 ebenfalls heiß diskutierte Themen, wobei die Weigerung von FreeBSD, eine bestimmte Implementierung zu unterstützen, von vielen als Beispiel für den übermäßigen Konservatismus von Core angeführt wurde. Zum Glück für alle erwies sich unsere abwartende Haltung als richtig, als die beiden großen "konkurrierenden" Gruppen, KAME und INRIA, schließlich zustimmten, ihre Implementierungen zusammenzulegen. Wir haben uns dazu verpflichtet, diese zusammengefasste Implementierung zu übernehmen und haben mehrere Mitarbeiter aus den KAME/INRIA-Gruppen im FreeBSD-Entwicklungsteam, die diese Implementierung importieren werden.



Auch am VM-System und am Dateisystem-Code wird intensiv gearbeitet, wobei ein Großteil davon entweder im Stillen in kleinen Gruppen (Dillon/Dyson/Greenman) getestet wird oder auf den 4.0-Zweig wartet, der immer noch für den 15. Januar 1999 geplant ist. In anderen Bereichen haben wir Kazus sehr begrüßenswertes komplettes Redesign des Konsolentreibers, das zusammen mit der USB-Unterstützung, die von Nick Hibma und anderen zur Verfügung gestellt wurde, in -current kommt. Dies sind nur einige der laufenden Projekte, und ich möchte niemanden beleidigen, indem ich seine Projekte nicht direkt erwähne, es sind nur 3 laufende Projekte, die mir gerade in den Sinn kommen. Wir scheinen eine Menge technischen Schwung zu bekommen, und das ist großartig, solange wir auch in den Zeiten, in denen sich nicht alle einig sind, welche technische Richtung wir einschlagen sollen, einen kühlen Kopf bewahren können.

== Technische Unterstützung:

Ein Punkt, der eigentlich jedem klar sein sollte, aber trotzdem immer wieder betont werden muss, ist die Tatsache, dass wir die Teilnahme an diesem Projekt als etwas aufrechterhalten müssen, das auch für die Entwickler/Teilnehmer _angenehm_ ist, sonst werden sie genauso schnell wieder verschwinden und aufhören, jedem einzelnen von uns den Nutzen ihrer freiwilligen Arbeit zukommen zu lassen (auf die man nicht einmal einen Dollarwert setzen könnte). Das ist etwas, dessen sich jeder unserer Benutzer bewusst sein sollte, zumindest irgendwo im Hinterkopf, wenn er versucht ist, FreeBSD als eine weitere Einschweißlösung von Software, Inc. zu betrachten und die Projektmitglieder wie persönliche Mitarbeiter zu behandeln. Diejenigen, die auf der Suche nach echten FreeBSD-Mitarbeitern sind, sollten eine E-Mail an jobs@FreeBSD.org schicken und angeben, wie viel Geld sie zu zahlen bereit sind, andernfalls lassen Sie es bleiben.

Ich will hier nicht so hart rüberkommen, dass die Leute sich nicht einmal die Mühe machen, uns um Hilfe zu bitten, ich sage nur, dass die Benutzer, die die verschiedenen FreeBSD Mechanismen für freiwillige technische Unterstützung nutzen (Mail, News, IRC, etc.), immer verstehen sollten, dass es nicht viel anders ist, einen völlig Fremden um Hilfe zu bitten, als eine beliebige Person auf der Straße um einen Dollar zu bitten. Wenn du kostenlose Hilfe bekommen willst, solltest du zumindest lernen, höflich zu fragen und ein "Nein" als Antwort zu akzeptieren! :-) Ich habe im letzten Jahr eine Menge Missbrauch von Freiwilligen in den technischen Supportforen gesehen, und das nervt ehrlich gesagt. Die Leute müssen einfach rücksichtsvoller sein und aufhören, kostenlosen technischen Support als ein gottgegebenes Recht und nicht als ein besonderes Privileg zu betrachten. Wenn Sie technischen Support auf Abruf wünschen, gehen Sie auf www.freebsdmall.com und schließen Sie einen Vertrag für technischen Support ab. Sie bekommen das, wofür Sie bezahlen! :)

== Ein Blick nach vorn:

Was sehe ich für 1999 voraus? Nun, vorausgesetzt, wir verschwinden nicht alle in einem Holocaust vor der Jahrtausendwende, sehe ich mehr interessante neue Funktionen, verbessertes Marketing, mehr kommerzielles Interesse, mehr Zeitschriftenartikel und Presseaufmerksamkeit, im Grunde mehr vom Gleichen, wenn wir nur versuchen können, uns einigermaßen auf das zu konzentrieren, was wir tun müssen, und uns nicht davon ablenken lassen, seltsamen Desktop-Träumen hinterherzujagen oder plötzlich übermäßig minimalistisch oder einseitig in /usr/src zu werden, und weiterhin den Mittelweg zu gehen, für den wir bekannt sind. Das FreeBSD-Core-Team, das nun ein Jahr älter und hoffentlich auch etwas weiser ist, muss weiterhin eine leichte, aber ruhige Hand am Ruder behalten und sich wie gewohnt auf unsere Entwickler verlassen, die einen Großteil der eigentlichen Antriebskraft hinter FreeBSD liefern.

Ich hoffe, dass 1999 das Jahr sein wird, in dem mehr lokale Benutzergruppen und andere Selbsthilfeorganisationen gegründet werden. Das Handbuch und die FAQ sind Dokumente, die immer besser werden, ein weiterer Trend, der sich hoffentlich auch 1999 fortsetzen wird, wenn Nik Clayton, unser furchtloser neuer Leiter des Documentation Projects, das Ruder übernimmt. Wir dürfen jedoch nicht vergessen, daß für viele Benutzer das Handbuch und die FAQ nicht ausreichen.

Linux ist vor allem deshalb so erfolgreich, weil es über ein großes Unterstützungs- und Evangelisationsnetzwerk verfügt, das es ihm ermöglicht, diese Menschen zu erreichen und ihnen die Botschaft zu vermitteln. Wenn die FreeBSD-Anwender selbst wollen, dass FreeBSD besser abschneidet als die von ihnen am meisten wahrgenommene Konkurrenz - und 1998 war sicherlich ein Jahr, in dem ich viele Klagen darüber gehört habe -, dann müssen sie einfach ihren Hintern hochkriegen und mehr von dieser Art von Arbeit investieren. Wann hat sich das letzte Mal eine Gruppe von FreeBSD-Anwendern zusammengetan, um FreeBSD-Literatur bei einer Microsoft-Produktvorstellung zu verteilen, oder einen Install-a-thon auf einer lokalen Computermesse veranstaltet?


Die Linux-Leute machen so etwas anscheinend ständig, während nur einige wenige eingefleischte FreeBSD-Anwender es derzeit tun, warum also diesen Leuten nicht helfen? Treten Sie der Mailingliste advocacy@FreeBSD.org bei und diskutieren Sie dort Ihre Pläne, so dass andere, die mehr Enthusiasmus als Ideen haben, auch von Ihren Plänen lernen und Ihnen vielleicht helfen können. Schreiben Sie kurze Artikel für die neuen Advocacy-Seiten wie http://www.daemonnews.org/[www.daemonnews.org] oder http://www.freebsdrocks.com/[www.freebsdrocks.com] und helfen Sie, den Erfolg der evangelikalen BSD-Publikationen zu fördern.

Sätze wie "Das ist Ihr FreeBSD" und "Es hängt alles von Ihnen ab" mögen abgenutzt und abgedroschen erscheinen, aber sie sind leider immer noch wahr, obwohl es so wenige von uns und so viele von Ihnen gibt. Wenn FreeBSD auch 1999 noch erfolgreich sein soll, wird es nur mit einer starken Beteiligung der Benutzer möglich sein, und das bedeutet Sie, liebe Benutzer! Gründen Sie eine lokale Benutzergruppe, spenden Sie einige Ihrer älteren CDs an die örtliche Bibliothek, versuchen Sie, ein kleines Unternehmen oder einen ISP davon zu überzeugen, FreeBSD zu benutzen - dies sind nur einige der vielen Dinge, die getan werden können, wenn Sie wirklich daran interessiert sind, etwas Energie in FreeBSD zu stecken, und Ideen, was zu tun ist, werden die geringsten Ihrer Sorgen sein, wenn Sie wirklich motiviert sind.

Zusammenfassung: 1999, rah rah rah, let's do it! :)
