---
title: "FreeBSD/i386-Projekt"
sidenav: developers
---

include::shared/de/urls.adoc[]

= FreeBSD/i386-Projekt

[[Einleitung]]
== Einführung

Diese Seite enthält Informationen über die FreeBSD/i386-Plattform. FreeBSD/i386 sollte jede CPU, die mit dem Intel(T) 80486 oder besser kompatibel ist, im 32-Bit-Modus unterstützen. Fast alle neueren AMD(T)- und Intel(T)-CPUs sind jedoch auch in der Lage, im 64-Bit-Modus zu laufen, wenn Sie den Port link:../amd64/[FreeBSD/amd64] verwenden.

FreeBSD/i386 unterstützt standardmäßig bis zu 4GiB RAM. Maschinen mit mehr RAM müssen entweder link:../amd64/[FreeBSD/amd64] oder link:{faq}#memory-i386-over-4gb[Physical Address Extension (PAE)] verwenden, um den Speicher oberhalb der 4GiB-Grenze nutzen zu können.

== Status

FreeBSD/i386 läuft im 32-Bit-Multiuser-Modus, sowohl in Uniprozessor- als auch in Multiprozessor-Systemen.

Die i386-Plattform ist eine link:{committers-guide}#archs[Tier 1] FreeBSD-Plattform bis FreeBSD 12.x.
Ab FreeBSD 13.0 ist sie eine link:{committers-guide}#archs[Tier 2]-Plattform.
