---
title: "FreeBSD-Dokumentationsprojekt"
sidenav: docs
---

= FreeBSD Dokumentationsprojekt

== Überblick

Sich in ein neues und komplexes Betriebssystem einzuarbeiten, ist immer eine schwierige Aufgabe, egal wie schön die Benutzeroberfläche ist. FreeBSD ist in dieser Hinsicht nicht anders.

Es gibt zwar eine große Anzahl von Büchern über BSD Unix (und allgemein über UNIX(R)), aber FreeBSD hat seine eigenen, einzigartigen Eigenschaften, Verfahren und Eigenheiten.

Darüber hinaus ist FreeBSD für einige seiner Benutzer der erste Kontakt mit einem Unix-ähnlichen Betriebssystem, so dass die Verfügbarkeit einer qualitativ hochwertigen und genauen Dokumentation von größter Bedeutung ist.

Das FreeBSD Dokumentationsprojekt soll helfen, diese Lücke zu schließen. Dies geschieht auf zwei Arten:

. Die Mitglieder des Documentation Projects schreiben Dokumentationen und reichen sie zur Aufnahme in das _FreeBSD Documentation Set_ ein.

. Mitglieder des Documentation Projects diskutieren und gestalten die Formatierung und Organisation des _FreeBSD Documentation Set_.

[.tblbasic]
[width="100%",cols="100%",]
|===
a|
[.center]
=== Aktuelle Projekte

Es gibt eine Reihe von Projekten, die derzeit im Rahmen der Dokumentationsbemühungen _in Bearbeitung_ sind. Bitte nehmen Sie sich die Zeit, https://wiki.freebsd.org/Doc/IdeaList[die aktuelle Liste der Projekte] durchzusehen und zu schauen, ob es etwas gibt, bei dem *Sie* helfen können.
|===

== link:who[Wer wir sind, wie man Mitglied wird]

Diese Seite erklärt, wer das Dokumentationsprojekt ausmacht und wie Sie mitmachen können.

== link:doc-set[Das FreeBSD-Dokumentationspaket]

Diese Seite beschreibt die Komponenten des FreeBSD Documentation Set und die Art der Arbeit, die das Documentation Project mit ihnen leistet.

== link:submitting[Beiträge einreichen]

Das Einreichen von Beiträgen ist der beste Weg, um Teil des Projekts zu werden und die Benutzung von FreeBSD einfacher zu machen. Diese Seite erklärt, wie Sie Ihre Beiträge am besten einreichen, damit sie so schnell wie möglich bearbeitet werden können.

== link:translations[Übersetzungen]

Übersetzungen der FreeBSD-Dokumentation, der Webseiten, des Handbuchs, der Manual-Seiten und der FAQ.
