---
title: "FreeBSD Documentation Project: Die FreeBSD-Dokumentation"
sidenav: docs
---

= FreeBSD Documentation Project: Die FreeBSD-Dokumentation

Die Dokumentation von FreeBSD lässt sich in drei grundlegende Kategorien einteilen:

. https://man.freebsd.org/cgi/man.cgi[*Die Handbuchseiten*]
+
Die Handbuchseiten (Man Pages) sind Teil des Basissystems, aber auch ein wichtiger Bestandteil der Dokumentation. Sowohl das Dokumentationsprojekt als auch die Source-Committer aktualisieren und pflegen die Handbuchseiten.
+
Zurzeit hat das japanische Team viele der Handbuchseiten übersetzt. Andere Freiwillige könnten helfen, die Handbuchseiten auch in andere Sprachen zu übersetzen.
link:.../.../docs/books/[*Die Bücher*]
+
Das Projekt verfügt über eine große Anzahl von Dokumenten, die "Buchlänge" haben, oder auf dem Weg dahin sind. Dazu gehören die FreeBSD-FAQ und das FreeBSD-Handbuch.
link:../../docs/books#ARTICLES[*Die Artikel*]
+
FreeBSD bietet eine Fülle von Informationen in Form von kürzeren Artikeln - ähnlich wie die Tutorien oder HOWTO-Dokumentationen anderer Projekte.

link:..[Startseite des FreeBSD Dokumentationsprojekts]
