---
title: "FreeBSD Documentation Project: Beiträge einreichen"
sidenav: docs
---

include::shared/de/urls.adoc[]

= FreeBSD Dokumentationsprojekt: Dokumentation einreichen

== Ich habe eine Dokumentation geschrieben. Wie kann ich sie einreichen?

Zunächst einmal vielen Dank, dass Sie sich die Zeit genommen haben, dies zu tun.

Sie sollten Ihre Dokumentation dem Dokumentationsprojekt zur Überprüfung zur Verfügung stellen. Wenn Sie können, laden Sie sie irgendwo auf eine Webseite hoch.

Dann schreiben Sie eine Nachricht an die Mailingliste `FreeBSD-doc` mit einem kurzen Abriss der Dokumentation und einem Verweis auf den Ort, an dem sie sich befindet, und bitten um Rückmeldungen.

Wenn Sie die Dokumentation aus irgendeinem Grund nicht auf eine Website stellen können, können Sie sie direkt an die Mailingliste `FreeBSD-doc` schicken. Wenn Sie dies tun, senden Sie bitte nur Dokumente im Klartext.

Vielleicht möchten Sie eine Bitte um Kommentare zusätzlich an eine andere geeignete Mailingliste senden. Zum Beispiel wäre etwas, das sich auf die Benutzung von Subversion bezieht, um seinen Source-Tree auf dem neuesten Stand zu halten, für die Abonnenten der `FreeBSD-stable` Mailingliste von Interesse. Bitte nur höchstens eine andere Mailingliste in CC: nehmen.

Nachdem die Leute Ihre Dokumentation durchgesehen haben, und Sie die Möglichkeit hatten, deren Vorschläge zu berücksichtigen, können Sie sie an uns als finalisiert übergeben.

Der korrekte Weg dazu ist, einen Problembericht zu erstellen. Eine Anleitung dazu finden Sie unter link:../../support/bugreports/[Fehlerberichte].

Sie tun dies, damit Ihr Beitrag nachverfolgt werden kann. Wenn Sie einen PR (Problembericht) einreichen, wird ihm eine eindeutige Nummer zugewiesen. Einer der Committer kann den PR dann sich selbst zuweisen und sich mit Ihnen bei der Übermittlung der neuen Dokumentation abstimmen. Weitere Informationen finden Sie unter link:{problem-reports}[FreeBSD Problemberichte erstellen].

Stellen Sie sicher, dass das "Produkt" auf "Documentation" und die "Komponente" auf "Documentation" oder "Website" eingestellt ist. Fügen Sie dem PR Ihre erstellten Dateien bei. Bitte geben Sie auch Links zu den Mailinglisteneinträgen an, in denen Ihre Änderungen diskutiert wurden, falls zutreffend.

== Ich habe ein bereits vorhandenes Dokument verbessert. Wie kann ich meine Korrekturen einreichen?

Nochmals vielen Dank, dass Sie unsere Dokumentation verbessern wollen.

Als erstes müssen Sie eine spezielle Datei, eine sogenannte Differenz (_diff_), erstellen. Diese Datei enthält nur die Änderungen, die Sie vorgenommen haben. Das macht es für die Person, die die Anfrage bearbeitet, einfacher zu sehen, was Sie geändert haben, und bedeutet, dass Sie nicht viel Zeit darauf verwenden müssen, zu erklären, was Sie geändert haben (obwohl Sie trotzdem erklären sollten, warum Sie denken, dass die Änderung gemacht werden sollte).

Um eine Differenz (eine "diff-Datei") zu erstellen, gehen Sie wie folgt vor:

. Erstellen Sie eine Kopie der Datei, die Sie ändern wollen. Wenn Sie zum Beispiel `foo.xml` ändern, machen Sie
+
....
    % cp foo.xml foo.xml.old
....
. Nehmen Sie dann Ihre Änderungen an foo.xml vor.
+
....
    % vi foo.xml
    ... tipp tipp tipp ...

    ... testen Sie die Änderungen, prüfen Sie sie auf Tippfehler und so weiter ...
....
. Erstellen Sie den Diff. Der Befehl dazu lautet:
+
....
    % diff -u foo.xml.old foo.xml > foo.diff
....
+
Mit diesem Befehl werden die beiden Dateien verglichen und die Unterschiede in die Datei `foo.diff` geschrieben.

Sie können dann `foo.diff` an das Projekt zurückschicken. Senden Sie einen PR wie oben beschrieben und hängen Sie die Datei `foo.diff` an den PR an.

== Weitere Lektüre

* link:{fdp-primer}[Dokumentationsprojekt-Fibel für neue Mitwirkende]
* link:../[FreeBSD Documentation Project Home]
