---
title: "FreeBSD Documentation Project: Wer sind wir?"
sidenav: docs
---

include::shared/de/urls.adoc[]

= FreeBSD Dokumentationsprojekt: Wer sind wir, wie wird man Mitglied?

Das Dokumentationsprojekt besteht aus einem losen Zusammenschluss verschiedener Personen, die alle die Mailingliste FreeBSD-doc@FreeBSD.org abbonniert haben.

Einige von uns können Änderungen direkt in den FreeBSD-Dokumentationsbaum übertragen. Es gibt eine vollständige Liste der link:{contributors}#staff-committers[alle FreeBSD-Entwickler mit Commit-Rechten], sowie eine Liste der link:../../administration/#t-doceng[Haupt-Committer für das FreeBSD Documentation Project].

Andere haben keine Commit-Rechte, schreiben aber trotzdem Dokumentation und reichen diese ein. Sobald ein Beitrag über link:../submitting[Beiträge einreichen] eingereicht wurde, wird er von einem der Committer überprüft und in die Dokumentation aufgenommen.

Um beim Dokumentationsprojekt mitzuhelfen (und wir hoffen sehr, dass Sie das tun), abonnieren Sie einfach die Mailingliste und nehmen Sie teil. Sobald Sie das getan haben, sind Sie ein Mitglied des Projekts.

link:..[Startseite des FreeBSD Dokumentatiosprojekts]
